version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:REGION:YOUR_ACCOUNT_ID:task-definition/husky-bridge-frontend:REVISION",
        LoadBalancerInfo:
          ContainerName: "husky-bridge-frontend"
          ContainerPort: 80
        PlatformVersion: "LATEST"
Hooks:
  - BeforeInstall: "arn:aws:lambda:REGION:YOUR_ACCOUNT_ID:function:CodeDeployHook_BeforeInstall"
  - AfterInstall: "arn:aws:lambda:REGION:YOUR_ACCOUNT_ID:function:CodeDeployHook_AfterInstall"
  - AfterAllowTestTraffic: "arn:aws:lambda:REGION:YOUR_ACCOUNT_ID:function:CodeDeployHook_AfterAllowTestTraffic"
  - BeforeAllowTraffic: "arn:aws:lambda:REGION:YOUR_ACCOUNT_ID:function:CodeDeployHook_BeforeAllowTraffic"
  - AfterAllowTraffic: "arn:aws:lambda:REGION:YOUR_ACCOUNT_ID:function:CodeDeployHook_AfterAllowTraffic"

